target_channel: "@ednews_ru"
parser_url: "https://rg.ru/tema/obshestvo/obrazovanie"
parser_interval: 3600
publish_delay: 5400
debug: true

max_posts_per_run: 1
max_auto_post_length: 25000

filters:
  manual_review_words:
    - "спам"
    - "казино"
    - "крипта"
    - "ставки"
    - "скам"
    - "мошенни"

  ad_filter_words:
    - "купить"
    - "заказать"
    - "цена"
    - "стоимость"
    - "скидка"
    - "акция"
    - "распродажа"
    - "доставка"
    - "оптом"
    - "розница"
    - "магазин"
    - "интернет-магазин"
    - "оформление"
    - "промокод"
    - "бесплатно"
    - "реклама"
    - "спонсор"
    - "партнер"
    - "подпишись"
    - "переходи"
    - "ссылка"
    - "телеграм"
    - "канал"
    - "чат"
    - "бот"
    - "приобрести"
    - "продажа"
    - "товар"
    - "услуга"

  max_ad_words_count: 3
  queue_page_size: 10

  ad_patterns:
    - "\\b\\d{3,}\\s?руб\\b"
    - "\\b\\d+\\s?₽\\b"
    - "\\$\\s?\\d+"
    - "\\b\\d+\\s?%?\\s?скидк"
    - "@\\w+"
    - "t\\.me/\\w+"
    - "http[s]?://"